#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          bucketwrist,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftfrontdrive, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftbackdrive, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightfrontdrive, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightbackdrive, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftassembly1, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftassembly2, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


task main()
{
	motor[leftfrontdrive] = 100;
	motor[rightfrontdrive] = 100;
	motor[leftbackdrive] = 100;
	motor[rightbackdrive] = 100;
	wait10Msec(150);

	motor[leftfrontdrive] = -100;
	motor[rightfrontdrive] = 100;
	motor[leftbackdrive] = -100;
	motor[rightbackdrive] = 100;
	wait10Msec(50);

	motor[leftfrontdrive] = 100;
	motor[rightfrontdrive] = 100;
	motor[leftbackdrive] = 100;
	motor[rightbackdrive] = 100;
	wait10Msec(100);



}
