#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S4,     irsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          bucketwrist,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftfrontdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftbackdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightfrontdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightbackdrive, tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     liftassembly1, tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     liftassembly2, tmotorTetrix, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
	while(SensorValue[irsensor] != 7){

motor[leftfrontdrive] = 100;
motor[leftbackdrive] = 100;
motor[rightfrontdrive] = 100;
motor[rightbackdrive] = 100;
}
motor[leftfrontdrive] = 100;
motor[leftbackdrive] = 100;
motor[rightfrontdrive] = 100;
motor[rightbackdrive] = 100;
wait10Msec(15);

motor[leftfrontdrive] = 0;
motor[leftbackdrive] = 0;
motor[rightfrontdrive] = 0;
motor[rightbackdrive] = 0;
wait10Msec(10);

motor[leftfrontdrive] = 100;
motor[leftbackdrive] = 100;
motor[rightfrontdrive] = -100;
motor[rightbackdrive] = -100;
wait10Msec(83);

motor[leftfrontdrive] = 0;
motor[leftbackdrive] = 0;
motor[rightfrontdrive] = 0;
motor[rightbackdrive] = 0;
wait10Msec(5);

if(SensorValue(ultrasonic) < 30){
	while(SensorValue(ultrasonic) < 30){
motor[leftfrontdrive] = -100;
motor[leftbackdrive] = -100;
motor[rightfrontdrive] = -100;
motor[rightbackdrive] = -100;
}
}

motor[leftfrontdrive] = 0;
motor[leftbackdrive] = 0;
motor[rightfrontdrive] = 0;
motor[rightbackdrive] = 0;


motor[liftassembly1] = 100;
wait10Msec(600);
motor[liftassembly1] = 0;








if(SensorValue(ultrasonic) > 30){
	while(SensorValue(ultrasonic) > 30){
motor[leftfrontdrive] = 100;
motor[leftbackdrive] = 100;
motor[rightfrontdrive] = 100;
motor[rightbackdrive] = 100;
}
}
motor[leftfrontdrive] = 0;
motor[leftbackdrive] = 0;
motor[rightfrontdrive] = 0;
motor[rightbackdrive] = 0;

motor[bucketwrist] = -100;
wait10Msec(500);
motor[bucketwrist] = 0;

motor[leftfrontdrive] = -100;
motor[leftbackdrive] = -100;
motor[rightfrontdrive] = -100;
motor[rightbackdrive] = -100;

wait10Msec(25);

motor[leftfrontdrive] = 0;
motor[leftbackdrive] = 0;
motor[rightfrontdrive] = 0;
motor[rightbackdrive] = 0;
wait10Msec(5);

motor[liftassembly1] = -100;

wait10Msec(83);
wait10Msec(242);

motor[liftassembly1] = 0;

motor[leftfrontdrive] = 100;
motor[leftbackdrive] = 100;
motor[rightfrontdrive] = -100;
motor[rightbackdrive] = -100;
wait10Msec(45);

motor[leftfrontdrive] = 0;
motor[leftbackdrive] = 0;
motor[rightfrontdrive] = 0;
motor[rightbackdrive] = 0;

while(SensorValue(ultrasonic) > 40){

motor[liftassembly1] = -100;
motor[leftfrontdrive] = 100;
motor[leftbackdrive] = 100;
motor[rightfrontdrive] = 100;
motor[rightbackdrive] = 100;
}

motor[leftfrontdrive] = 0;
motor[leftbackdrive] = 0;
motor[rightfrontdrive] = 0;
motor[rightbackdrive] = 0;






}
