#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S4,     irsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          bucketwrist,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftfrontdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftbackdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightfrontdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightbackdrive, tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     liftassembly1, tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     liftassembly2, tmotorTetrix, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void DriveMotorsForward()
{
	motor[leftfrontdrive] = 100;
	motor[leftbackdrive] = 100;
	motor[rightfrontdrive] = 100;
	motor[rightbackdrive] = 100;
}

void StopDriveMotors()
{
	motor[leftfrontdrive] = 0;
	motor[leftbackdrive] = 0;
	motor[rightfrontdrive] = 0;
	motor[rightbackdrive] = 0;
}

void DriveMotorsBackward()
{
	motor[leftfrontdrive] = -100;
	motor[leftbackdrive] = -100;
	motor[rightfrontdrive] = -100;
	motor[rightbackdrive] = -100;
}

void TurnRight()
{
	motor[leftfrontdrive] = 100;
	motor[leftbackdrive] = 100;
	motor[rightfrontdrive] = -100;
	motor[rightbackdrive] = -100;
}
void TurnLeft()
{
	motor[leftfrontdrive] = -100;
	motor[leftbackdrive] = -100;
	motor[rightfrontdrive] = 100;
	motor[rightbackdrive] = 100;
}
task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

	while(SensorValue[irsensor] != 7)
	{

		DriveMotorsForward();
	}

	wait10Msec(15);

	StopDriveMotors();

	wait10Msec(10);

	TurnRight();

	wait10Msec(83);

	StopDriveMotors();

	wait10Msec(5);

	if(SensorValue(ultrasonic) < 30)
	{
		while(SensorValue(ultrasonic) < 30)
		{
			DriveMotorsBackward();
		}
	}

	StopDriveMotors();


	motor[liftassembly1] = 100;
	wait10Msec(600);
	motor[liftassembly1] = 0;


	if(SensorValue(ultrasonic) > 30)
	{
		while(SensorValue(ultrasonic) > 30)
		{
			DriveMotorsForward();
		}
	}
	StopDriveMotors();


	motor[bucketwrist] = -100;
	wait10Msec(500);
	motor[bucketwrist] = 0;

	DriveMotorsBackward();

	wait10Msec(25);

	StopDriveMotors();
	wait10Msec(5);

	motor[liftassembly1] = -100;
	wait10Msec(325);

	motor[liftassembly1] = 0;

	wait10Msec(30);

	TurnRight();
	wait1Msec(1000);

	StopDriveMotors();
	wait10Msec(30);

	while(SensorValue(ultrasonic) > 40)
	{
		DriveMotorsForward();
	}
	StopDriveMotors();
	wait10Msec(30);

	TurnLeft();        //Turn to be perpendicular to ramp
	wait10Msec(100);
	StopDriveMotors();
	wait10Msec(30);

	DriveMotorsForward(); // Drive alongside  ramp
	wait10Msec(200);
	StopDriveMotors();
	wait10Msec(30);

	TurnLeft();           // turn to face ramp
	wait10Msec(98);
	StopDriveMotors();
	wait10Msec(30);

	DriveMotorsForward();  //Drive onto ramp (hopefully)
	wait10Msec(300);
	StopDriveMotors();
}
