#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S4,     irsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          bucketwrist,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftfrontdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftbackdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightfrontdrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightbackdrive, tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     liftassembly1, tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     liftassembly2, tmotorTetrix, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void DriveMotorsForward()
{
	motor[leftfrontdrive] = 100;
	motor[leftbackdrive] = 100;
	motor[rightfrontdrive] = 100;
	motor[rightbackdrive] = 100;
}

void StopDriveMotors()
{
	motor[leftfrontdrive] = 0;
	motor[leftbackdrive] = 0;
	motor[rightfrontdrive] = 0;
	motor[rightbackdrive] = 0;
}

void DriveMotorsBackward()
{
	motor[leftfrontdrive] = -100;
	motor[leftbackdrive] = -100;
	motor[rightfrontdrive] = -100;
	motor[rightbackdrive] = -100;
}

void TurnRight()
{
	motor[leftfrontdrive] = 100;
	motor[leftbackdrive] = 100;
	motor[rightfrontdrive] = -100;
	motor[rightbackdrive] = -100;
}

void TurnLeft()
{
	motor[leftfrontdrive] = -100;
	motor[leftbackdrive] = -100;
	motor[rightfrontdrive] = 100;
	motor[rightbackdrive] = 100;
}


#include "JoystickDriver.c"
task main()
{
	while(SensorValue[irsensor] != 7)
	{

		DriveMotorsForward();
	}

	wait10Msec(15);

	StopDriveMotors();

	wait10Msec(10);

	TurnRight();

	wait10Msec(83);

	StopDriveMotors();

	wait10Msec(5);



	while(SensorValue(ultrasonic) < 30)
	{
			DriveMotorsBackward();
	}


	StopDriveMotors();


	motor[liftassembly1] = 100;
	wait10Msec(600);
	motor[liftassembly1] = 0;



	while(SensorValue(ultrasonic) > 30)
	{
		DriveMotorsForward();
	}

	StopDriveMotors();

	motor[bucketwrist] = -100;
	wait10Msec(500);
	motor[bucketwrist] = 0;

	DriveMotorsBackward();

	wait10Msec(25);

	StopDriveMotors();
	wait10Msec(5);

	motor[liftassembly1] = -100;
	wait10Msec(325);

	motor[liftassembly1] = 0;

	TurnRight();
	wait1Msec(455);

	StopDriveMotors();

	while(SensorValue(ultrasonic) > 40)
	{
		motor[liftassembly1] = -100;
		DriveMotorsForward();
	}
	StopDriveMotors();
	wait10Msec(3);

	TurnLeft();    //Turn to be perpendicular to ramp
	wait1Msec(455);
	StopDriveMotors();
	wait10Msec(3);

	DriveMotorsForward(); // Drive alongside  ramp
	wait10Msec(100);
	StopDriveMotors();
	wait10Msec(3);


	TurnLeft();        // turn to face ramp
	wait1Msec(455);
	StopDriveMotors();
	wait10Msec(3);

	DriveMotorsForward();  //Drive onto ramp (hopefully)
	wait10Msec(50);
	StopDriveMotors();
	wait10Msec(3);

  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  988,    7); wait1Msec(  75);  // Note(E, Duration(32th))
  PlayTone( 1047,    7); wait1Msec(  75);  // Note(F, Duration(32th))
  PlayTone( 1109,    7); wait1Msec(  75);  // Note(F#, Duration(32th))
  PlayTone( 1175,    7); wait1Msec(  75);  // Note(G, Duration(32th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1047,   14); wait1Msec( 150);  // Note(F, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1047,   14); wait1Msec( 150);  // Note(F, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  880,  108); wait1Msec(1200);  // Note(D, Duration(Half))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  831,  108); wait1Msec(1200);  // Note(C#, Duration(Half))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  784,  108); wait1Msec(1200);  // Note(C, Duration(Half))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  932,   14); wait1Msec( 150);  // Note(A#5, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))


}
